package type;

/**
 * type/RepeatUnitListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

public final class RepeatUnitListHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.RepeatUnit value[] = null;

    public RepeatUnitListHolder() {
    }

    public RepeatUnitListHolder(final type.RepeatUnit[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.RepeatUnitListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.RepeatUnitListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.RepeatUnitListHelper.write(o, value);
    }

}
