package seqdb;

/**
* seqdb/BioSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/seqdb.idl
* Monday, August 23, 2004 12:02:46 PM BST
*/


/** 
       * generic biosequence. Provides al functionality we would like to see 
       * on any sequence.
       */
public final class BioSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public seqdb.BioSeq value = null;

  public BioSeqHolder ()
  {
  }

  public BioSeqHolder (seqdb.BioSeq initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = seqdb.BioSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    seqdb.BioSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return seqdb.BioSeqHelper.type ();
  }

}
