package seqdb;


/**
* seqdb/BioSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/seqdb.idl
* Monday, August 23, 2004 12:02:46 PM BST
*/


/** 
       * generic biosequence. Provides al functionality we would like to see 
       * on any sequence.
       */
abstract public class BioSeqHelper
{
  private static String  _id = "IDL:seqdb/BioSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, seqdb.BioSeq that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static seqdb.BioSeq extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (seqdb.BioSeqHelper.id (), "BioSeq");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static seqdb.BioSeq read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BioSeqStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, seqdb.BioSeq value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static seqdb.BioSeq narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof seqdb.BioSeq)
      return (seqdb.BioSeq)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      seqdb._BioSeqStub stub = new seqdb._BioSeqStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
