package seqdb;


/**
* seqdb/BioSeq.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/seqdb.idl
* Monday, August 23, 2004 12:02:46 PM BST
*/


/** 
       * generic biosequence. Provides al functionality we would like to see 
       * on any sequence.
       */
public interface BioSeq extends BioSeqOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BioSeq
