package seqdb;


/**
* seqdb/Feature.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/seqdb.idl
* Monday, August 23, 2004 12:02:46 PM BST
*/


/**
       * generic Feature. Only has a key to identify it's type, an ID to 
       * identify the instance and a version.
       */
public interface Feature extends FeatureOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Feature
