package seqdb;


/**
* seqdb/FeatureOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/seqdb.idl
* Monday, August 23, 2004 12:02:46 PM BST
*/


/**
       * generic Feature. Only has a key to identify it's type, an ID to 
       * identify the instance and a version.
       */
public interface FeatureOperations 
{

  /**
  	 * feature identifier.
  	 */
  String getFeatureId ();

  /**
  	 * Feature types are defined by a key.
  	 */
  String getKey ();

  /**
  	 * return current version of the feature. returns 0 if 
  	 * no versioning is implemented.
  	 */
  int getFeatureVersion ();
} // interface FeatureOperations
