package seqdb;

/**
 * seqdb/SeqInfo.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/seqdb.idl Monday, August 23, 2004 12:02:46 PM BST
 */

/**
 * Information associated with a sequence
 */
public interface SeqInfo extends SeqInfoOperations, org.omg.CORBA.Object,
        org.omg.CORBA.portable.IDLEntity {
} // interface SeqInfo
