package seqdb;

/**
 * seqdb/SeqInfoOperations.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/seqdb.idl Monday, August 23, 2004
 * 12:02:46 PM BST
 */

/**
 * Information associated with a sequence
 */
public interface SeqInfoOperations {

    /**
     * sequence of comments, describing the characteristics of the sequence
     */
    String[] getComments() throws type.NoResult;

    /**
     * cross references to other databases containing related or additional
     * information
     */
    type.DbXref[] getDbXrefs() throws type.NoResult;

    /**
     * short (one line) description
     */
    String getDescription() throws type.NoResult;

    /**
     * sequence of keywords, describing the characteristics of the sequence
     */
    String[] getKeywords() throws type.NoResult;

    /**
     * cross references to the EMBL publication database information
     */
    type.DbXref[] getReferences() throws type.NoResult;
} // interface SeqInfoOperations
