package seqdb;


/**
* seqdb/SeqInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/seqdb.idl
* Monday, August 23, 2004 12:02:46 PM BST
*/


/**
       * Information associated with a sequence
       */
abstract public class SeqInfoHelper
{
  private static String  _id = "IDL:seqdb/SeqInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, seqdb.SeqInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static seqdb.SeqInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (seqdb.SeqInfoHelper.id (), "SeqInfo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static seqdb.SeqInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_SeqInfoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, seqdb.SeqInfo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static seqdb.SeqInfo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof seqdb.SeqInfo)
      return (seqdb.SeqInfo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      seqdb._SeqInfoStub stub = new seqdb._SeqInfoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
