package nsdb;

/**
* nsdb/CommitFailedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public final class CommitFailedHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.CommitFailed value = null;

  public CommitFailedHolder ()
  {
  }

  public CommitFailedHolder (nsdb.CommitFailed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.CommitFailedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.CommitFailedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.CommitFailedHelper.type ();
  }

}
