package nsdb;


/**
* nsdb/EmblHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/


/**
 * Entry point for Nucleotide Sequence Database.
 * Query methods on the database are defined here.
 * Currently this is minimal, but should be extended later on.
 */
abstract public class EmblHelper
{
  private static String  _id = "IDL:nsdb/Embl:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.Embl that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.Embl extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (nsdb.EmblHelper.id (), "Embl");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.Embl read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EmblStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.Embl value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static nsdb.Embl narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nsdb.Embl)
      return (nsdb.Embl)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nsdb._EmblStub stub = new nsdb._EmblStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
