package nsdb;


/**
* nsdb/EmblWriter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public interface EmblWriter extends EmblWriterOperations, nsdb.Embl, org.omg.CORBA.portable.IDLEntity 
{
} // interface EmblWriter
