package nsdb;

/**
* nsdb/EmblSeqWriterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public final class EmblSeqWriterHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.EmblSeqWriter value = null;

  public EmblSeqWriterHolder ()
  {
  }

  public EmblSeqWriterHolder (nsdb.EmblSeqWriter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.EmblSeqWriterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.EmblSeqWriterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.EmblSeqWriterHelper.type ();
  }

}
