package nsdb;


/**
* nsdb/EmblWriterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public interface EmblWriterOperations  extends nsdb.EmblOperations
{

  /**
       * Retrieve a writable Nucleotide sequence object, given a
       * sequence_id.
       * @raises type::NoResult if the given sequence_id does not exist.
       */
  nsdb.EmblSeqWriter getEmblSeqWriter (String sequence_id) throws type.NoResult;

  /**
       *  Return a ServerInfo structure for the server.
       **/
  nsdb.ServerInfo getServerInfo ();
} // interface EmblWriterOperations
