package nsdb;

/**
* nsdb/EmblWriterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public final class EmblWriterHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.EmblWriter value = null;

  public EmblWriterHolder ()
  {
  }

  public EmblWriterHolder (nsdb.EmblWriter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.EmblWriterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.EmblWriterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.EmblWriterHelper.type ();
  }

}
