package nsdb;

/**
* nsdb/EmblSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/


/**
       * EMBL Nucleotide sequence interface. An EMBL sequence contains all information
       * to generate a flat-file entry out of it.
       * It defines no new behaviour but inherits from 
       * several interfaces and acts as a container of the combined functionality.
       */
public final class EmblSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.EmblSeq value = null;

  public EmblSeqHolder ()
  {
  }

  public EmblSeqHolder (nsdb.EmblSeq initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.EmblSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.EmblSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.EmblSeqHelper.type ();
  }

}
