package nsdb;


/**
* nsdb/EntryInfoListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/

abstract public class EntryInfoListHelper
{
  private static String  _id = "IDL:nsdb/EntryInfoList:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.EntryInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.EntryInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = nsdb.EntryInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (nsdb.EntryInfoListHelper.id (), "EntryInfoList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.EntryInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    nsdb.EntryInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new nsdb.EntryInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = nsdb.EntryInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.EntryInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      nsdb.EntryInfoHelper.write (ostream, value[_i0]);
  }

}
