package nsdb;


/**
* nsdb/EntryStats.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class EntryStats implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public int last_change_time = (int)0;

  public EntryStats ()
  {
  } // ctor

  public EntryStats (String _name, int _last_change_time)
  {
    name = _name;
    last_change_time = _last_change_time;
  } // ctor

} // class EntryStats
