package nsdb;


/**
* nsdb/FeatureLocationHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Location of a NucFeature
       * This interface does not allow to change the nuc_feature
       * If a location is assigned to a nucfeature, the inverse relation
       * should be properly updated
       * @see NucFeature.getLocation
       */
abstract public class FeatureLocationHelper
{
  private static String  _id = "IDL:nsdb/FeatureLocation:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.FeatureLocation that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.FeatureLocation extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (nsdb.FeatureLocationHelper.id (), "FeatureLocation");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.FeatureLocation read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_FeatureLocationStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.FeatureLocation value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static nsdb.FeatureLocation narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nsdb.FeatureLocation)
      return (nsdb.FeatureLocation)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nsdb._FeatureLocationStub stub = new nsdb._FeatureLocationStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
