package nsdb;


/**
* nsdb/InexactLocation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/

public final class InexactLocation extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InexactLocation ()
  {
    super(InexactLocationHelper.id());
  } // ctor

  public InexactLocation (String _reason)
  {
    super(InexactLocationHelper.id());
    reason = _reason;
  } // ctor


  public InexactLocation (String $reason, String _reason)
  {
    super(InexactLocationHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InexactLocation
