package nsdb;


/**
* nsdb/InvalidKey.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public final class InvalidKey extends org.omg.CORBA.UserException
{

  public InvalidKey ()
  {
    super(InvalidKeyHelper.id());
  } // ctor


  public InvalidKey (String $reason)
  {
    super(InvalidKeyHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidKey
