package nsdb;

/**
* nsdb/InvalidQualifierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class InvalidQualifierHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.InvalidQualifier value = null;

  public InvalidQualifierHolder ()
  {
  }

  public InvalidQualifierHolder (nsdb.InvalidQualifier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.InvalidQualifierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.InvalidQualifierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.InvalidQualifierHelper.type ();
  }

}
