package nsdb;


/**
* nsdb/InvalidQualifier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class InvalidQualifier extends org.omg.CORBA.UserException
{

  public InvalidQualifier ()
  {
    super(InvalidQualifierHelper.id());
  } // ctor


  public InvalidQualifier (String $reason)
  {
    super(InvalidQualifierHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidQualifier
