package nsdb;


/**
* nsdb/Location.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * A location is built from one or more nodes forming a tree
       * local node IDs are only unique within a location tree
       * the root node has id == 0
       * the Node id defines the position of the node in the sequence<LocationNode>
       * The value is relative to the current (parent) node
       * e.g if the current node is at position x in the LocationNodes sequence
       *     and there is a childId with value j
       *     then the position of this child in the LocationNodes sequence will be x+j
       */
public interface Location extends LocationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

  /**
         * The sequence segment is derived from another sequence
         */
  public static final int VirtualSegment_ltc = (int)(1);

  /**
         * The sequence segment is explicitly given as a DNA string.
         */
  public static final int PhysicalSegment_ltc = (int)(2);

  /**
         * Sequence is unknown. Only it's (estimated) size in known.
         */
  public static final int Gap_ltc = (int)(3);

  /**
         * defines how to link a set of LocationNodes
         */
  public static final int Operator_ltc = (int)(4);
} // interface Location
