package nsdb;

/**
* nsdb/LocationParseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class LocationParseHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.LocationParse value = null;

  public LocationParseHolder ()
  {
  }

  public LocationParseHolder (nsdb.LocationParse initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.LocationParseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.LocationParseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.LocationParseHelper.type ();
  }

}
