package nsdb;


/**
* nsdb/NucFeature.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Nucleotide Sequence Feature interface. Features are <I>owned</I> by a
       * sequence and contain information about that (and maybe other) sequence.
       * The relation between the feature and the sequence is defined by it's
       * location.
       * @see Location
       */
public interface NucFeature extends NucFeatureOperations, seqdb.Feature, org.omg.CORBA.portable.IDLEntity 
{

  // values 1-100 are reserved for EBI QualifierTypeCodes
  public static final int string_qtc = (int)(1);
  public static final int boolean_qtc = (int)(2);
  public static final int integer_qtc = (int)(3);
  public static final int real_qtc = (int)(4);
  public static final int TranslationException_qtc = (int)(17);
  public static final int CodonTranslation_qtc = (int)(18);
  public static final int Anticodon_qtc = (int)(19);
  public static final int SpliceConsensus_qtc = (int)(20);
  public static final int RepeatUnit_qtc = (int)(21);
  public static final int DbXref_qtc = (int)(22);
} // interface NucFeature
