package nsdb;


/**
* nsdb/NucFeatureHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Nucleotide Sequence Feature interface. Features are <I>owned</I> by a
       * sequence and contain information about that (and maybe other) sequence.
       * The relation between the feature and the sequence is defined by it's
       * location.
       * @see Location
       */
abstract public class NucFeatureHelper
{
  private static String  _id = "IDL:nsdb/NucFeature:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.NucFeature that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.NucFeature extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (nsdb.NucFeatureHelper.id (), "NucFeature");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.NucFeature read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NucFeatureStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.NucFeature value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static nsdb.NucFeature narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nsdb.NucFeature)
      return (nsdb.NucFeature)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nsdb._NucFeatureStub stub = new nsdb._NucFeatureStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
