package nsdb;

/**
* nsdb/NucFeatureWriterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public final class NucFeatureWriterHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.NucFeatureWriter value = null;

  public NucFeatureWriterHolder ()
  {
  }

  public NucFeatureWriterHolder (nsdb.NucFeatureWriter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.NucFeatureWriterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.NucFeatureWriterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.NucFeatureWriterHelper.type ();
  }

}
