package nsdb;


/**
* nsdb/NucSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/


/**
       * Generic Nucleotide sequence interface.
       * The accession number is retrieved using the getBioSeqId method inherited from BioSeq.
       * @see EmblSeq
       * @see seqdb::BioSeq
       */
abstract public class NucSeqHelper
{
  private static String  _id = "IDL:nsdb/NucSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.NucSeq that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.NucSeq extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (nsdb.NucSeqHelper.id (), "NucSeq");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.NucSeq read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_NucSeqStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.NucSeq value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static nsdb.NucSeq narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nsdb.NucSeq)
      return (nsdb.NucSeq)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nsdb._NucSeqStub stub = new nsdb._NucSeqStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
