package nsdb;

/**
* nsdb/OutOfDateHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class OutOfDateHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.OutOfDate value = null;

  public OutOfDateHolder ()
  {
  }

  public OutOfDateHolder (nsdb.OutOfDate initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.OutOfDateHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.OutOfDateHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.OutOfDateHelper.type ();
  }

}
