package nsdb;

/**
* nsdb/ReadOnlyExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class ReadOnlyExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.ReadOnlyException value = null;

  public ReadOnlyExceptionHolder ()
  {
  }

  public ReadOnlyExceptionHolder (nsdb.ReadOnlyException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.ReadOnlyExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.ReadOnlyExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.ReadOnlyExceptionHelper.type ();
  }

}
