package nsdb.EmblPackage;


/**
* nsdb/EmblPackage/SupercededHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/

abstract public class SupercededHelper
{
  private static String  _id = "IDL:nsdb/Embl/Superceded:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.EmblPackage.Superceded that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.EmblPackage.Superceded extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (type.stringListHelper.id (), "stringList", _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "bio_seq_ids",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (nsdb.EmblPackage.SupercededHelper.id (), "Superceded", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.EmblPackage.Superceded read (org.omg.CORBA.portable.InputStream istream)
  {
    nsdb.EmblPackage.Superceded value = new nsdb.EmblPackage.Superceded ();
    // read and discard the repository ID
    istream.read_string ();
    value.bio_seq_ids = type.stringListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.EmblPackage.Superceded value)
  {
    // write the repository ID
    ostream.write_string (id ());
    type.stringListHelper.write (ostream, value.bio_seq_ids);
  }

}
