package nsdb.EmblPackage;

/**
* nsdb/EmblPackage/SupercededHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/

public final class SupercededHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.EmblPackage.Superceded value = null;

  public SupercededHolder ()
  {
  }

  public SupercededHolder (nsdb.EmblPackage.Superceded initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.EmblPackage.SupercededHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.EmblPackage.SupercededHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.EmblPackage.SupercededHelper.type ();
  }

}
