package type;

/**
* type/NoResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:36 PM BST
*/


/**
   * If a query in a database returns no results, the NoResult is raised
   */
public final class NoResultHolder implements org.omg.CORBA.portable.Streamable
{
  public type.NoResult value = null;

  public NoResultHolder ()
  {
  }

  public NoResultHolder (type.NoResult initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.NoResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.NoResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.NoResultHelper.type ();
  }

}
