package type;


/**
* type/RepeatUnitListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

abstract public class RepeatUnitListHelper
{
  private static String  _id = "IDL:type/RepeatUnitList:1.0";

  public static void insert (org.omg.CORBA.Any a, type.RepeatUnit[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static type.RepeatUnit[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = type.RepeatUnitHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (type.RepeatUnitListHelper.id (), "RepeatUnitList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static type.RepeatUnit[] read (org.omg.CORBA.portable.InputStream istream)
  {
    type.RepeatUnit value[] = null;
    int _len0 = istream.read_long ();
    value = new type.RepeatUnit[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = type.RepeatUnitHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, type.RepeatUnit[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      type.RepeatUnitHelper.write (ostream, value[_i0]);
  }

}
