package seqdb;

/**
 * seqdb/SeqInfoHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/seqdb.idl Monday, August 23, 2004 12:02:46 PM BST
 */

/**
 * Information associated with a sequence
 */
public final class SeqInfoHolder implements org.omg.CORBA.portable.Streamable {
    public seqdb.SeqInfo value = null;

    public SeqInfoHolder() {
    }

    public SeqInfoHolder(final seqdb.SeqInfo initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = seqdb.SeqInfoHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return seqdb.SeqInfoHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        seqdb.SeqInfoHelper.write(o, value);
    }

}
