package type;

/**
 * type/IndexOutOfRange.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

/**
 * If a number indicating a position in a sequence is outside the limits of the
 * sequence, or more elements are associated to an object than it can handle, an
 * IndexOutOfRange exception is raised
 */
public final class IndexOutOfRange extends org.omg.CORBA.UserException {
    public String reason = null;

    public IndexOutOfRange() {
        super(IndexOutOfRangeHelper.id());
    } // ctor

    public IndexOutOfRange(final String _reason) {
        super(IndexOutOfRangeHelper.id());
        reason = _reason;
    } // ctor

    public IndexOutOfRange(final String $reason, final String _reason) {
        super(IndexOutOfRangeHelper.id() + "  " + $reason);
        reason = _reason;
    } // ctor

} // class IndexOutOfRange
