package type;

/**
 * type/InvalidArgumentValue.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:36 PM BST
 */

/**
 * controlled values (i.e. an attribute can only contain a value taken from a
 * well defined range of values, or an in parameter to a method has a restricted
 * set of acceptable values) are presented as typescodes, used in as union. If a
 * method tries to set a controlled value attribute/parameter to an invalid
 * value, an invalidValue is raised
 */
public final class InvalidArgumentValue extends org.omg.CORBA.UserException {
    public String reason = null;

    public InvalidArgumentValue() {
        super(InvalidArgumentValueHelper.id());
    } // ctor

    public InvalidArgumentValue(final String _reason) {
        super(InvalidArgumentValueHelper.id());
        reason = _reason;
    } // ctor

    public InvalidArgumentValue(final String $reason, final String _reason) {
        super(InvalidArgumentValueHelper.id() + "  " + $reason);
        reason = _reason;
    } // ctor

} // class InvalidArgumentValue
