package nsdb;


/**
* nsdb/EmblSeqOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/


/**
       * EMBL Nucleotide sequence interface. An EMBL sequence contains all information
       * to generate a flat-file entry out of it.
       * It defines no new behaviour but inherits from 
       * several interfaces and acts as a container of the combined functionality.
       */
public interface EmblSeqOperations  extends nsdb.NucSeqOperations, seqdb.SeqInfoOperations, nsdb.EntryInfoOperations
{
} // interface EmblSeqOperations
