package nsdb;


/**
* nsdb/EmblSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/


/**
       * EMBL Nucleotide sequence interface. An EMBL sequence contains all information
       * to generate a flat-file entry out of it.
       * It defines no new behaviour but inherits from 
       * several interfaces and acts as a container of the combined functionality.
       */
abstract public class EmblSeqHelper
{
  private static String  _id = "IDL:nsdb/EmblSeq:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.EmblSeq that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.EmblSeq extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (nsdb.EmblSeqHelper.id (), "EmblSeq");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.EmblSeq read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EmblSeqStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.EmblSeq value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static nsdb.EmblSeq narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof nsdb.EmblSeq)
      return (nsdb.EmblSeq)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      nsdb._EmblSeqStub stub = new nsdb._EmblSeqStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
