package nsdb;


/**
* nsdb/FeatureLocationListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:39 PM BST
*/

public final class FeatureLocationListHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.FeatureLocation value[] = null;

  public FeatureLocationListHolder ()
  {
  }

  public FeatureLocationListHolder (nsdb.FeatureLocation[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.FeatureLocationListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.FeatureLocationListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.FeatureLocationListHelper.type ();
  }

}
