package nsdb;

/**
* nsdb/FeatureLocationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Location of a NucFeature
       * This interface does not allow to change the nuc_feature
       * If a location is assigned to a nucfeature, the inverse relation
       * should be properly updated
       * @see NucFeature.getLocation
       */
public final class FeatureLocationHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.FeatureLocation value = null;

  public FeatureLocationHolder ()
  {
  }

  public FeatureLocationHolder (nsdb.FeatureLocation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.FeatureLocationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.FeatureLocationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.FeatureLocationHelper.type ();
  }

}
