package nsdb;


/**
* nsdb/NucFeatureWriter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:44 PM BST
*/

public interface NucFeatureWriter extends NucFeatureWriterOperations, nsdb.NucFeature, org.omg.CORBA.portable.IDLEntity 
{
} // interface NucFeatureWriter
