package nsdb;


/**
* nsdb/NucSeqListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:39 PM BST
*/

public final class NucSeqListHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.NucSeq value[] = null;

  public NucSeqListHolder ()
  {
  }

  public NucSeqListHolder (nsdb.NucSeq[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.NucSeqListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.NucSeqListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.NucSeqListHelper.type ();
  }

}
