package nsdb;


/**
* nsdb/QualifierParse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb_write.idl
* Monday, August 23, 2004 12:02:43 PM BST
*/

public final class QualifierParse extends org.omg.CORBA.UserException
{
  public String reason = null;

  public QualifierParse ()
  {
    super(QualifierParseHelper.id());
  } // ctor

  public QualifierParse (String _reason)
  {
    super(QualifierParseHelper.id());
    reason = _reason;
  } // ctor


  public QualifierParse (String $reason, String _reason)
  {
    super(QualifierParseHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class QualifierParse
