package type;

/**
 * type/AminoAcidListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

public final class AminoAcidListHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.AminoAcid value[] = null;

    public AminoAcidListHolder() {
    }

    public AminoAcidListHolder(final type.AminoAcid[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.AminoAcidListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.AminoAcidListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.AminoAcidListHelper.write(o, value);
    }

}
