package type;


/**
* type/AminoAcidHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * Amino Acid. This can be any amino acid, including modified or unusual ones.
   * <P>
   * <dl>
   * <dt> code
   * <dd> <A href="http://www.ebi.ac.uk/ebi_docs/embl_db/ft/aa_abbrevs.html">
   *     IUPAC-IUB</A> one-letter code if the amino acid has one assigned
   * <dd> othwerwise the code will be a blank character
   * <dt> name
   * <dd> descriptive name of the
   *     <A href="http://www.ebi.ac.uk/ebi_docs/embl_db/ft/aa_abbrevs.html">
   *      Amino Acid</A> or 
   *      <A href="http://www.ebi.ac.uk/ebi_docs/embl_db/ft/modified_aa.html">
   *      modified or unusual Amino Acid</A>
   * <dt> abbreviation
   * <dd> abbreviated name of the
   *     <A href="http://www.ebi.ac.uk/ebi_docs/embl_db/ft/aa_abbrevs.html">
   *      Amino Acid</A> or 
   *      <A href="http://www.ebi.ac.uk/ebi_docs/embl_db/ft/modified_aa.html">
   *      modified or unusual Amino Acid</A>
   *</dl>
   */
abstract public class AminoAcidHelper
{
  private static String  _id = "IDL:type/AminoAcid:1.0";

  public static void insert (org.omg.CORBA.Any a, type.AminoAcid that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static type.AminoAcid extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_char);
          _members0[0] = new org.omg.CORBA.StructMember (
            "code",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "abbreviation",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (type.AminoAcidHelper.id (), "AminoAcid", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static type.AminoAcid read (org.omg.CORBA.portable.InputStream istream)
  {
    type.AminoAcid value = new type.AminoAcid ();
    value.code = istream.read_char ();
    value.name = istream.read_string ();
    value.abbreviation = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, type.AminoAcid value)
  {
    ostream.write_char (value.code);
    ostream.write_string (value.name);
    ostream.write_string (value.abbreviation);
  }

}
