package type;


/**
* type/AntiCodon.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * Location of the anticodon of tRNA and the amino acid for which
   * it codes.
   * <p>
   * <dl>
   * <dt> start
   * <dd> start position of the anticodon
   * <dt> end
   * <dd> end position of the anticodon
   * <dt> amino_acid
   * <dd> amino acid used. 
   * <dd> No modified AA are allowed.
   * </dl>
   */
public final class AntiCodon implements org.omg.CORBA.portable.IDLEntity
{
  public int start = (int)0;
  public int end = (int)0;
  public type.AminoAcid amino_acid = null;

  public AntiCodon ()
  {
  } // ctor

  public AntiCodon (int _start, int _end, type.AminoAcid _amino_acid)
  {
    start = _start;
    end = _end;
    amino_acid = _amino_acid;
  } // ctor

} // class AntiCodon
