package type;

/**
 * type/AntiCodonListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

public final class AntiCodonListHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.AntiCodon value[] = null;

    public AntiCodonListHolder() {
    }

    public AntiCodonListHolder(final type.AntiCodon[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.AntiCodonListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.AntiCodonListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.AntiCodonListHelper.write(o, value);
    }

}
