package type;

/**
 * type/CodonTranslationHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

/**
 * Translation rule specifying the amino acid encoded by a codon. Standard rules
 * are defined by the genetic code of an organism. If a CDS uses non-standard
 * rules, this can be annotated with qualifier codon (value type
 * CodonTranslation_s).
 * <p>
 * <dt>codon
 * <dd>literal sequence of the codon.
 * <dt>amino_acid
 * <dd>amino acid used.
 * <dd>No modified AA are allowed.
 */
public final class CodonTranslationHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.CodonTranslation value = null;

    public CodonTranslationHolder() {
    }

    public CodonTranslationHolder(final type.CodonTranslation initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.CodonTranslationHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.CodonTranslationHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.CodonTranslationHelper.write(o, value);
    }

}
