package type;


/**
* type/CodonTranslationListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public final class CodonTranslationListHolder implements org.omg.CORBA.portable.Streamable
{
  public type.CodonTranslation value[] = null;

  public CodonTranslationListHolder ()
  {
  }

  public CodonTranslationListHolder (type.CodonTranslation[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.CodonTranslationListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.CodonTranslationListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.CodonTranslationListHelper.type ();
  }

}
