package type;

/**
 * type/DbXrefHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:37 PM BST
 */

/**
 * Database cross-reference. The list of valid database identifiers used by the
 * collaboration is defined at the <A
 * href="http://www.ncbi.nlm.nih.gov/collab/db_xref.html">NCBI collaborative web
 * server</A>
 * <dl>
 * <dt>db
 * <dd>database identifier
 * <dt>primary_id
 * <dd>object identifier in the database
 * <dt>version
 * <dd>if the referenced database supports versioning, version refers to the
 * version of the object, when the cross-reference was generated. If can be used
 * to verify that a cross-reference is up to date.
 * <dt>label
 * <dd>secondary identifier, possibly used to indicate a sub/super-part of the
 * primary object or an alternative name to the primary id. The label can
 * contain information for the convenience of the user, but no assumptions
 * should be made on the long-term stability of it.
 * </dl>
 */
public final class DbXrefHolder implements org.omg.CORBA.portable.Streamable {
    public type.DbXref value = null;

    public DbXrefHolder() {
    }

    public DbXrefHolder(final type.DbXref initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.DbXrefHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.DbXrefHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.DbXrefHelper.write(o, value);
    }

}
