package type;


/**
* type/DbXref.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * Database cross-reference. The list of valid database identifiers
   * used by the collaboration is defined at the 
   * <A href="http://www.ncbi.nlm.nih.gov/collab/db_xref.html">NCBI
      collaborative web server</A> 
   * <dl>
   * <dt>db
   * <dd>database identifier
   * <dt>primary_id
   * <dd>object identifier in the database
   * <dt>version
   * <dd> if the referenced database supports versioning, version
   *      refers to the version of the object, when the cross-reference 
   *      was generated. If can be used to verify that a cross-reference
   *      is up to date.
   * <dt>label
   * <dd>secondary identifier, possibly used to indicate a sub/super-part of
   *     the primary object or an alternative name to the primary id. 
   *     The label can contain information for the convenience
   *     of the user, but no assumptions should be made on the long-term 
   *     stability of it.
   * </dl>
   */
public final class DbXref implements org.omg.CORBA.portable.IDLEntity
{
  public String db = null;
  public String primary_id = null;
  public int version = (int)0;
  public String label = null;

  public DbXref ()
  {
  } // ctor

  public DbXref (String _db, String _primary_id, int _version, String _label)
  {
    db = _db;
    primary_id = _primary_id;
    version = _version;
    label = _label;
  } // ctor

} // class DbXref
