package type;


/**
* type/Exact_ftc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public interface Exact_ftc
{

  /**
     * value is an exact position
     */
  public static final int value = (int)(1);
}
