package type;

/**
 * type/FuzzyHelper.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:37 PM BST
 */

abstract public class FuzzyHelper {
    private static String _id = "IDL:type/Fuzzy:1.0";

    private static org.omg.CORBA.TypeCode __typeCode = null;

    private static boolean __active = false;

    public static type.Fuzzy extract(final org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    public static String id() {
        return _id;
    }

    public static void insert(final org.omg.CORBA.Any a, final type.Fuzzy that) {
        final org.omg.CORBA.portable.OutputStream out = a
                .create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static type.Fuzzy read(
            final org.omg.CORBA.portable.InputStream istream) {
        final type.Fuzzy value = new type.Fuzzy();
        value.value = istream.read_long();
        value.size = istream.read_long();
        value.type = istream.read_long();
        return value;
    }

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            synchronized (org.omg.CORBA.TypeCode.class) {
                if (__typeCode == null) {
                    if (__active) {
                        return org.omg.CORBA.ORB.init()
                                .create_recursive_tc(_id);
                    }
                    __active = true;
                    final org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember[3];
                    org.omg.CORBA.TypeCode _tcOf_members0 = null;
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(
                            org.omg.CORBA.TCKind.tk_long);
                    _members0[0] = new org.omg.CORBA.StructMember("value",
                            _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(
                            org.omg.CORBA.TCKind.tk_long);
                    _members0[1] = new org.omg.CORBA.StructMember("size",
                            _tcOf_members0, null);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().get_primitive_tc(
                            org.omg.CORBA.TCKind.tk_long);
                    _tcOf_members0 = org.omg.CORBA.ORB.init().create_alias_tc(
                            type.FuzzyTypeCodeHelper.id(), "FuzzyTypeCode",
                            _tcOf_members0);
                    _members0[2] = new org.omg.CORBA.StructMember("type",
                            _tcOf_members0, null);
                    __typeCode = org.omg.CORBA.ORB.init().create_struct_tc(
                            type.FuzzyHelper.id(), "Fuzzy", _members0);
                    __active = false;
                }
            }
        }
        return __typeCode;
    }

    public static void write(final org.omg.CORBA.portable.OutputStream ostream,
            final type.Fuzzy value) {
        ostream.write_long(value.value);
        ostream.write_long(value.size);
        ostream.write_long(value.type);
    }

}
