package type;

/**
 * type/FuzzyTypeCodeHelper.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

/**
 * a position can be fuzzy. FuzzyType defines how to interprete the combination
 * of value and size, to define the range of fuzziness. Currently values 1-5 are
 * in use. 5-10 are reserved for future use.
 */
abstract public class FuzzyTypeCodeHelper {
    private static String _id = "IDL:type/FuzzyTypeCode:1.0";

    private static org.omg.CORBA.TypeCode __typeCode = null;

    public static int extract(final org.omg.CORBA.Any a) {
        return read(a.create_input_stream());
    }

    public static String id() {
        return _id;
    }

    public static void insert(final org.omg.CORBA.Any a, final int that) {
        final org.omg.CORBA.portable.OutputStream out = a
                .create_output_stream();
        a.type(type());
        write(out, that);
        a.read_value(out.create_input_stream(), type());
    }

    public static int read(final org.omg.CORBA.portable.InputStream istream) {
        int value = 0;
        value = istream.read_long();
        return value;
    }

    synchronized public static org.omg.CORBA.TypeCode type() {
        if (__typeCode == null) {
            __typeCode = org.omg.CORBA.ORB.init().get_primitive_tc(
                    org.omg.CORBA.TCKind.tk_long);
            __typeCode = org.omg.CORBA.ORB.init().create_alias_tc(
                    type.FuzzyTypeCodeHelper.id(), "FuzzyTypeCode", __typeCode);
        }
        return __typeCode;
    }

    public static void write(final org.omg.CORBA.portable.OutputStream ostream,
            final int value) {
        ostream.write_long(value);
    }

}
