package type;

/**
 * type/In_ftc.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.1" from corba/types.idl Monday, August 23, 2004 12:02:37 PM BST
 */

public interface In_ftc {

    /**
     * A single base chosen from a range or span of bases is indicated by the
     * first base number (value) and the last base number of the range
     * (value+size) inclusive.
     */
    public static final int value = (2);
}
