package type;

/**
 * type/IndexOutOfRangeHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:36 PM BST
 */

/**
 * If a number indicating a position in a sequence is outside the limits of the
 * sequence, or more elements are associated to an object than it can handle, an
 * IndexOutOfRange exception is raised
 */
public final class IndexOutOfRangeHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.IndexOutOfRange value = null;

    public IndexOutOfRangeHolder() {
    }

    public IndexOutOfRangeHolder(final type.IndexOutOfRange initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.IndexOutOfRangeHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.IndexOutOfRangeHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.IndexOutOfRangeHelper.write(o, value);
    }

}
