package type;


/**
* type/Less_ftc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public interface Less_ftc
{

  /**
     * an end point is undefined but behind (and does not include) the
     * base number specified in value.
     * size is unused.
     */
  public static final int value = (int)(4);
}
