package type;

/**
 * type/NoResult.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

/**
 * If a query in a database returns no results, the NoResult is raised
 */
public final class NoResult extends org.omg.CORBA.UserException {

    public NoResult() {
        super(NoResultHelper.id());
    } // ctor

    public NoResult(final String $reason) {
        super(NoResultHelper.id() + "  " + $reason);
    } // ctor

} // class NoResult
