package type;

/**
 * type/NoWritePermission.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:36 PM BST
 */

/**
 * If no write permission is granted (i.e. a set-method cannot be performed) the
 * NoWritePermission is raised
 */
public final class NoWritePermission extends org.omg.CORBA.UserException {
    public String reason = null;

    public NoWritePermission() {
        super(NoWritePermissionHelper.id());
    } // ctor

    public NoWritePermission(final String _reason) {
        super(NoWritePermissionHelper.id());
        reason = _reason;
    } // ctor

    public NoWritePermission(final String $reason, final String _reason) {
        super(NoWritePermissionHelper.id() + "  " + $reason);
        reason = _reason;
    } // ctor

} // class NoWritePermission
