package type;

/**
* type/ParseErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:36 PM BST
*/


/**
   * a sequence (e.g. string) with an expected defined format cannot be parsed
   */
public final class ParseErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public type.ParseError value = null;

  public ParseErrorHolder ()
  {
  }

  public ParseErrorHolder (type.ParseError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.ParseErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.ParseErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.ParseErrorHelper.type ();
  }

}
