package type;

/**
* type/PersonHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:36 PM BST
*/


/**
   * A person information : this is used to specify the authors
   * <p><dl>
   * <dt>surname
   * <dd>the person surname
   * <dt>firstname
   * <dd>the person firstname
   * <dt>midinitial
   * <dd>the person mid initial
   * <dl><p>
   */
public final class PersonHolder implements org.omg.CORBA.portable.Streamable
{
  public type.Person value = null;

  public PersonHolder ()
  {
  }

  public PersonHolder (type.Person initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.PersonHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.PersonHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.PersonHelper.type ();
  }

}
