package type;


/**
* type/PersonListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public final class PersonListHolder implements org.omg.CORBA.portable.Streamable
{
  public type.Person value[] = null;

  public PersonListHolder ()
  {
  }

  public PersonListHolder (type.Person[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.PersonListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.PersonListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.PersonListHelper.type ();
  }

}
