package type;


/**
* type/RepeatUnit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * A RepeatUnit identifies the exact unit that is being repeated. It can be
   * either a base range, or can refer to the label of a labeled repeat_unit
   * feature (but not both; this datatype is likely to be superceded by a
   * union). 
   * <dt> start
   * <dd> position of first base in the first occurrence of the repeated segment
   * <dt> end
   * <dd> position of the last base in first occurence of the repeated segment
   * <dt> label
   * <dd> Currently, usually a textual description of the repeating segment,
   *      but can refer to a labeled repeat_unit feature. 
   * This attribute may in future become a proper DbXref to a feature; 
   */
public final class RepeatUnit implements org.omg.CORBA.portable.IDLEntity
{
  public int start = (int)0;
  public int end = (int)0;
  public String label = null;

  public RepeatUnit ()
  {
  } // ctor

  public RepeatUnit (int _start, int _end, String _label)
  {
    start = _start;
    end = _end;
    label = _label;
  } // ctor

} // class RepeatUnit
