package type;

/**
* type/RepeatUnitHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * A RepeatUnit identifies the exact unit that is being repeated. It can be
   * either a base range, or can refer to the label of a labeled repeat_unit
   * feature (but not both; this datatype is likely to be superceded by a
   * union). 
   * <dt> start
   * <dd> position of first base in the first occurrence of the repeated segment
   * <dt> end
   * <dd> position of the last base in first occurence of the repeated segment
   * <dt> label
   * <dd> Currently, usually a textual description of the repeating segment,
   *      but can refer to a labeled repeat_unit feature. 
   * This attribute may in future become a proper DbXref to a feature; 
   */
public final class RepeatUnitHolder implements org.omg.CORBA.portable.Streamable
{
  public type.RepeatUnit value = null;

  public RepeatUnitHolder ()
  {
  }

  public RepeatUnitHolder (type.RepeatUnit initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.RepeatUnitHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.RepeatUnitHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.RepeatUnitHelper.type ();
  }

}
