/**
 * This document is a part of the source code and related artifacts for BiLab,
 * an open source interactive workbench for computational biologists.
 * 
 * http://computing.ornl.gov/
 * 
 * Copyright © 2011 Oak Ridge National Laboratory
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package type;

/**
 * type/RepeatUnit.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:37 PM BST
 */

/**
 * A RepeatUnit identifies the exact unit that is being repeated. It can be
 * either a base range, or can refer to the label of a labeled repeat_unit
 * feature (but not both; this datatype is likely to be superceded by a union).
 * <dt>start
 * <dd>position of first base in the first occurrence of the repeated segment
 * <dt>end
 * <dd>position of the last base in first occurence of the repeated segment
 * <dt>label
 * <dd>Currently, usually a textual description of the repeating segment, but
 * can refer to a labeled repeat_unit feature. This attribute may in future
 * become a proper DbXref to a feature;
 */
public final class RepeatUnit implements org.omg.CORBA.portable.IDLEntity {
    public int start = 0;
    public int end = 0;
    public String label = null;

    public RepeatUnit() {
    } // ctor

    public RepeatUnit(final int _start, final int _end, final String _label) {
        start = _start;
        end = _end;
        label = _label;
    } // ctor

} // class RepeatUnit
