package type;


/**
* type/RevisionListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public final class RevisionListHolder implements org.omg.CORBA.portable.Streamable
{
  public type.Revision value[] = null;

  public RevisionListHolder ()
  {
  }

  public RevisionListHolder (type.Revision[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.RevisionListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.RevisionListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.RevisionListHelper.type ();
  }

}
