package type;


/**
* type/SpliceConsensus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * flag to indicate that the splice site consensus sequence is not
   * present at one of the feature's splice junctions
   * If no qualifier is present, the default is that both splice sites 
   * contain the consensus
   */
public final class SpliceConsensus implements org.omg.CORBA.portable.IDLEntity
{
  public boolean five_cons = false;
  public boolean three_cons = false;

  public SpliceConsensus ()
  {
  } // ctor

  public SpliceConsensus (boolean _five_cons, boolean _three_cons)
  {
    five_cons = _five_cons;
    three_cons = _three_cons;
  } // ctor

} // class SpliceConsensus
