package type;

/**
 * type/SpliceConsensusListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

public final class SpliceConsensusListHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.SpliceConsensus value[] = null;

    public SpliceConsensusListHolder() {
    }

    public SpliceConsensusListHolder(final type.SpliceConsensus[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.SpliceConsensusListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.SpliceConsensusListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.SpliceConsensusListHelper.write(o, value);
    }

}
