package type;


/**
* type/SpliceConsensusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * flag to indicate that the splice site consensus sequence is not
   * present at one of the feature's splice junctions
   * If no qualifier is present, the default is that both splice sites 
   * contain the consensus
   */
abstract public class SpliceConsensusHelper
{
  private static String  _id = "IDL:type/SpliceConsensus:1.0";

  public static void insert (org.omg.CORBA.Any a, type.SpliceConsensus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static type.SpliceConsensus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[0] = new org.omg.CORBA.StructMember (
            "five_cons",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[1] = new org.omg.CORBA.StructMember (
            "three_cons",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (type.SpliceConsensusHelper.id (), "SpliceConsensus", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static type.SpliceConsensus read (org.omg.CORBA.portable.InputStream istream)
  {
    type.SpliceConsensus value = new type.SpliceConsensus ();
    value.five_cons = istream.read_boolean ();
    value.three_cons = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, type.SpliceConsensus value)
  {
    ostream.write_boolean (value.five_cons);
    ostream.write_boolean (value.three_cons);
  }

}
