package type;

/**
* type/SpliceConsensusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/


/**
   * flag to indicate that the splice site consensus sequence is not
   * present at one of the feature's splice junctions
   * If no qualifier is present, the default is that both splice sites 
   * contain the consensus
   */
public final class SpliceConsensusHolder implements org.omg.CORBA.portable.Streamable
{
  public type.SpliceConsensus value = null;

  public SpliceConsensusHolder ()
  {
  }

  public SpliceConsensusHolder (type.SpliceConsensus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.SpliceConsensusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.SpliceConsensusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.SpliceConsensusHelper.type ();
  }

}
