package type;

/**
 * type/stringListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:36 PM BST
 */

/**
 * sequence of strings.
 */
public final class stringListHolder implements
        org.omg.CORBA.portable.Streamable {
    public String value[] = null;

    public stringListHolder() {
    }

    public stringListHolder(final String[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.stringListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.stringListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.stringListHelper.write(o, value);
    }

}
