package type;


/**
* type/stringListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:36 PM BST
*/


/**
   * sequence of strings.
   */
public final class stringListHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public stringListHolder ()
  {
  }

  public stringListHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.stringListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.stringListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.stringListHelper.type ();
  }

}
