package type;


/**
* type/TranslationExceptionListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

abstract public class TranslationExceptionListHelper
{
  private static String  _id = "IDL:type/TranslationExceptionList:1.0";

  public static void insert (org.omg.CORBA.Any a, type.TranslationException[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static type.TranslationException[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = type.TranslationExceptionHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (type.TranslationExceptionListHelper.id (), "TranslationExceptionList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static type.TranslationException[] read (org.omg.CORBA.portable.InputStream istream)
  {
    type.TranslationException value[] = null;
    int _len0 = istream.read_long ();
    value = new type.TranslationException[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = type.TranslationExceptionHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, type.TranslationException[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      type.TranslationExceptionHelper.write (ostream, value[_i0]);
  }

}
