package type;

/**
 * type/TranslationExceptionListHolder.java . Generated by the IDL-to-Java
 * compiler (portable), version "3.1" from corba/types.idl Monday, August 23,
 * 2004 12:02:37 PM BST
 */

public final class TranslationExceptionListHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.TranslationException value[] = null;

    public TranslationExceptionListHolder() {
    }

    public TranslationExceptionListHolder(
            final type.TranslationException[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.TranslationExceptionListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.TranslationExceptionListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.TranslationExceptionListHelper.write(o, value);
    }

}
