package type;


/**
* type/ulongListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:36 PM BST
*/

public final class ulongListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public ulongListHolder ()
  {
  }

  public ulongListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.ulongListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.ulongListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.ulongListHelper.type ();
  }

}
