package type;

/**
 * type/ulongListHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

public final class ulongListHolder implements org.omg.CORBA.portable.Streamable {
    public int value[] = null;

    public ulongListHolder() {
    }

    public ulongListHolder(final int[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.ulongListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.ulongListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.ulongListHelper.write(o, value);
    }

}
