package nsdb.LocationPackage;

/**
* nsdb/LocationPackage/LocationNode_uHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/

public final class LocationNode_uHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.LocationPackage.LocationNode_u value = null;

  public LocationNode_uHolder ()
  {
  }

  public LocationNode_uHolder (nsdb.LocationPackage.LocationNode_u initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.LocationPackage.LocationNode_uHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.LocationPackage.LocationNode_uHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.LocationPackage.LocationNode_uHelper.type ();
  }

}
