package nsdb.LocationPackage;


/**
* nsdb/LocationPackage/LocationNodeListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/

public final class LocationNodeListHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.LocationPackage.LocationNode_u value[] = null;

  public LocationNodeListHolder ()
  {
  }

  public LocationNodeListHolder (nsdb.LocationPackage.LocationNode_u[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.LocationPackage.LocationNodeListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.LocationPackage.LocationNodeListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.LocationPackage.LocationNodeListHelper.type ();
  }

}
