package nsdb.LocationPackage;


/**
* nsdb/LocationPackage/LocGapHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * spacer between sequence fragments
       */
abstract public class LocGapHelper
{
  private static String  _id = "IDL:nsdb/Location/LocGap:1.0";

  public static void insert (org.omg.CORBA.Any a, type.Fuzzy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static type.Fuzzy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = type.FuzzyHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (nsdb.LocationPackage.LocGapHelper.id (), "LocGap", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static type.Fuzzy read (org.omg.CORBA.portable.InputStream istream)
  {
    type.Fuzzy value = null;
    value = type.FuzzyHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, type.Fuzzy value)
  {
    type.FuzzyHelper.write (ostream, value);
  }

}
