package type;

/**
 * type/ParseError.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

/**
 * a sequence (e.g. string) with an expected defined format cannot be parsed
 */
public final class ParseError extends org.omg.CORBA.UserException {
    public String reason = null;

    public ParseError() {
        super(ParseErrorHelper.id());
    } // ctor

    public ParseError(final String _reason) {
        super(ParseErrorHelper.id());
        reason = _reason;
    } // ctor

    public ParseError(final String $reason, final String _reason) {
        super(ParseErrorHelper.id() + "  " + $reason);
        reason = _reason;
    } // ctor

} // class ParseError
