package type;

/**
 * type/NoResultHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

/**
 * If a query in a database returns no results, the NoResult is raised
 */
public final class NoResultHolder implements org.omg.CORBA.portable.Streamable {
    public type.NoResult value = null;

    public NoResultHolder() {
    }

    public NoResultHolder(final type.NoResult initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.NoResultHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.NoResultHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.NoResultHelper.write(o, value);
    }

}
