package type;


/**
* type/Between_ftc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public interface Between_ftc
{

  /**
     * A site between two points (nucleotides), such as an endonucleolytic
     * cleavage site. The site is a single position between 2 consecutive bases
     * in the range. The range is defined by value, value+size (inclusive)
     */
  public static final int value = (int)(3);
}
