package seqdb;

/**
 * seqdb/_FeatureStub.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/seqdb.idl Monday, August 23, 2004 12:02:46 PM BST
 */

/**
 * generic Feature. Only has a key to identify it's type, an ID to identify the
 * instance and a version.
 */
public class _FeatureStub extends org.omg.CORBA.portable.ObjectImpl implements
        seqdb.Feature {

    // Type-specific CORBA::Object operations
    private static String[] __ids = { "IDL:seqdb/Feature:1.0" };

    @Override
    public String[] _ids() {
        return __ids.clone();
    }

    /**
     * feature identifier.
     */
    @Override
    public String getFeatureId() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            final org.omg.CORBA.portable.OutputStream $out = _request(
                    "getFeatureId", true);
            $in = _invoke($out);
            final String $result = $in.read_string();
            return $result;
        } catch (final org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            final String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (final org.omg.CORBA.portable.RemarshalException $rm) {
            return getFeatureId();
        } finally {
            _releaseReply($in);
        }
    } // getFeatureId

    /**
     * return current version of the feature. returns 0 if no versioning is
     * implemented.
     */
    @Override
    public int getFeatureVersion() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            final org.omg.CORBA.portable.OutputStream $out = _request(
                    "getFeatureVersion", true);
            $in = _invoke($out);
            final int $result = $in.read_ulong();
            return $result;
        } catch (final org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            final String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (final org.omg.CORBA.portable.RemarshalException $rm) {
            return getFeatureVersion();
        } finally {
            _releaseReply($in);
        }
    } // getFeatureVersion

    /**
     * Feature types are defined by a key.
     */
    @Override
    public String getKey() {
        org.omg.CORBA.portable.InputStream $in = null;
        try {
            final org.omg.CORBA.portable.OutputStream $out = _request("getKey",
                    true);
            $in = _invoke($out);
            final String $result = $in.read_string();
            return $result;
        } catch (final org.omg.CORBA.portable.ApplicationException $ex) {
            $in = $ex.getInputStream();
            final String _id = $ex.getId();
            throw new org.omg.CORBA.MARSHAL(_id);
        } catch (final org.omg.CORBA.portable.RemarshalException $rm) {
            return getKey();
        } finally {
            _releaseReply($in);
        }
    } // getKey

    private void readObject(final java.io.ObjectInputStream s)
            throws java.io.IOException {
        final String str = s.readUTF();
        final String[] args = null;
        final java.util.Properties props = null;
        final org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init(args, props)
                .string_to_object(str);
        final org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)
                ._get_delegate();
        _set_delegate(delegate);
    }

    private void writeObject(final java.io.ObjectOutputStream s)
            throws java.io.IOException {
        final String[] args = null;
        final java.util.Properties props = null;
        final String str = org.omg.CORBA.ORB.init(args, props)
                .object_to_string(this);
        s.writeUTF(str);
    }
} // class _FeatureStub
