package nsdb.NucFeaturePackage;


/**
* nsdb/NucFeaturePackage/QualifierValueListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:41 PM BST
*/

public final class QualifierValueListHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.NucFeaturePackage.QualifierValue_u value[] = null;

  public QualifierValueListHolder ()
  {
  }

  public QualifierValueListHolder (nsdb.NucFeaturePackage.QualifierValue_u[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.NucFeaturePackage.QualifierValueListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.NucFeaturePackage.QualifierValueListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.NucFeaturePackage.QualifierValueListHelper.type ();
  }

}
