package type;

/**
 * type/Person.java . Generated by the IDL-to-Java compiler (portable), version
 * "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

/**
 * A person information : this is used to specify the authors
 * <p>
 * <dl>
 * <dt>surname
 * <dd>the person surname
 * <dt>firstname
 * <dd>the person firstname
 * <dt>midinitial
 * <dd>the person mid initial
 * <dl>
 * <p>
 */
public final class Person implements org.omg.CORBA.portable.IDLEntity {
    public String surname = null;
    public String firstname = null;
    public String midinitial = null;

    public Person() {
    } // ctor

    public Person(final String _surname, final String _firstname,
            final String _midinitial) {
        surname = _surname;
        firstname = _firstname;
        midinitial = _midinitial;
    } // ctor

} // class Person
