package type;

/**
 * type/CodonTranslationListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.1" from corba/types.idl Monday, August 23, 2004
 * 12:02:37 PM BST
 */

public final class CodonTranslationListHolder implements
        org.omg.CORBA.portable.Streamable {
    public type.CodonTranslation value[] = null;

    public CodonTranslationListHolder() {
    }

    public CodonTranslationListHolder(final type.CodonTranslation[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.CodonTranslationListHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.CodonTranslationListHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.CodonTranslationListHelper.write(o, value);
    }

}
