package type;

/**
 * type/RevisionHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:37 PM BST
 */

/**
 * Revision
 * <dl>
 * <dt>date
 * <dd>datestamp of revision
 * <dt>type
 * <dd>type of revision. Valid types are defined in meta
 * </dl>
 */
public final class RevisionHolder implements org.omg.CORBA.portable.Streamable {
    public type.Revision value = null;

    public RevisionHolder() {
    }

    public RevisionHolder(final type.Revision initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.RevisionHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.RevisionHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.RevisionHelper.write(o, value);
    }

}
