package type;

/**
 * type/PersonHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/types.idl Monday, August 23, 2004 12:02:36 PM BST
 */

/**
 * A person information : this is used to specify the authors
 * <p>
 * <dl>
 * <dt>surname
 * <dd>the person surname
 * <dt>firstname
 * <dd>the person firstname
 * <dt>midinitial
 * <dd>the person mid initial
 * <dl>
 * <p>
 */
public final class PersonHolder implements org.omg.CORBA.portable.Streamable {
    public type.Person value = null;

    public PersonHolder() {
    }

    public PersonHolder(final type.Person initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = type.PersonHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return type.PersonHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        type.PersonHelper.write(o, value);
    }

}
