package seqdb;

/**
 * seqdb/FeatureHolder.java . Generated by the IDL-to-Java compiler (portable),
 * version "3.1" from corba/seqdb.idl Monday, August 23, 2004 12:02:46 PM BST
 */

/**
 * generic Feature. Only has a key to identify it's type, an ID to identify the
 * instance and a version.
 */
public final class FeatureHolder implements org.omg.CORBA.portable.Streamable {
    public seqdb.Feature value = null;

    public FeatureHolder() {
    }

    public FeatureHolder(final seqdb.Feature initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(final org.omg.CORBA.portable.InputStream i) {
        value = seqdb.FeatureHelper.read(i);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return seqdb.FeatureHelper.type();
    }

    @Override
    public void _write(final org.omg.CORBA.portable.OutputStream o) {
        seqdb.FeatureHelper.write(o, value);
    }

}
