package nsdb.LocationPackage;


/**
* nsdb/LocationPackage/IdListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/

public final class IdListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public IdListHolder ()
  {
  }

  public IdListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.LocationPackage.IdListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.LocationPackage.IdListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.LocationPackage.IdListHelper.type ();
  }

}
