package nsdb.LocationPackage;


/**
* nsdb/LocationPackage/LocVirtualSegmentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Virtual segment of a sequence.The sequence segment is derived from another sequence.
       * <p><dl>
       * <dt>bio_seq_id
       * <dd>sequence from which this segment is derived
       * <dd>contains an accession number
       * <dt>start
       * <dd>start position of segment (inclusive)
       * <dt>end
       * <dd>end position of segment (inclusive)
       * <dd>In the case that start defines a 'between' position, end is unused
       * <dt>complement
       * <dd> true if segment should be complemented before any further manipulations
       * </dl>
       */
abstract public class LocVirtualSegmentHelper
{
  private static String  _id = "IDL:nsdb/Location/LocVirtualSegment:1.0";

  public static void insert (org.omg.CORBA.Any a, nsdb.LocationPackage.LocVirtualSegment that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static nsdb.LocationPackage.LocVirtualSegment extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "bio_seq_id",
            _tcOf_members0,
            null);
          _tcOf_members0 = type.FuzzyHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "start",
            _tcOf_members0,
            null);
          _tcOf_members0 = type.FuzzyHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "end",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[3] = new org.omg.CORBA.StructMember (
            "complement",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (nsdb.LocationPackage.LocVirtualSegmentHelper.id (), "LocVirtualSegment", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static nsdb.LocationPackage.LocVirtualSegment read (org.omg.CORBA.portable.InputStream istream)
  {
    nsdb.LocationPackage.LocVirtualSegment value = new nsdb.LocationPackage.LocVirtualSegment ();
    value.bio_seq_id = istream.read_string ();
    value.start = type.FuzzyHelper.read (istream);
    value.end = type.FuzzyHelper.read (istream);
    value.complement = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, nsdb.LocationPackage.LocVirtualSegment value)
  {
    ostream.write_string (value.bio_seq_id);
    type.FuzzyHelper.write (ostream, value.start);
    type.FuzzyHelper.write (ostream, value.end);
    ostream.write_boolean (value.complement);
  }

}
