package nsdb.LocationPackage;


/**
* nsdb/LocationPackage/LocVirtualSegment.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Virtual segment of a sequence.The sequence segment is derived from another sequence.
       * <p><dl>
       * <dt>bio_seq_id
       * <dd>sequence from which this segment is derived
       * <dd>contains an accession number
       * <dt>start
       * <dd>start position of segment (inclusive)
       * <dt>end
       * <dd>end position of segment (inclusive)
       * <dd>In the case that start defines a 'between' position, end is unused
       * <dt>complement
       * <dd> true if segment should be complemented before any further manipulations
       * </dl>
       */
public final class LocVirtualSegment implements org.omg.CORBA.portable.IDLEntity
{
  public String bio_seq_id = null;
  public type.Fuzzy start = null;
  public type.Fuzzy end = null;
  public boolean complement = false;

  public LocVirtualSegment ()
  {
  } // ctor

  public LocVirtualSegment (String _bio_seq_id, type.Fuzzy _start, type.Fuzzy _end, boolean _complement)
  {
    bio_seq_id = _bio_seq_id;
    start = _start;
    end = _end;
    complement = _complement;
  } // ctor

} // class LocVirtualSegment
