package nsdb.LocationPackage;

/**
* nsdb/LocationPackage/LocVirtualSegmentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/nsdb.idl
* Monday, August 23, 2004 12:02:40 PM BST
*/


/**
       * Virtual segment of a sequence.The sequence segment is derived from another sequence.
       * <p><dl>
       * <dt>bio_seq_id
       * <dd>sequence from which this segment is derived
       * <dd>contains an accession number
       * <dt>start
       * <dd>start position of segment (inclusive)
       * <dt>end
       * <dd>end position of segment (inclusive)
       * <dd>In the case that start defines a 'between' position, end is unused
       * <dt>complement
       * <dd> true if segment should be complemented before any further manipulations
       * </dl>
       */
public final class LocVirtualSegmentHolder implements org.omg.CORBA.portable.Streamable
{
  public nsdb.LocationPackage.LocVirtualSegment value = null;

  public LocVirtualSegmentHolder ()
  {
  }

  public LocVirtualSegmentHolder (nsdb.LocationPackage.LocVirtualSegment initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = nsdb.LocationPackage.LocVirtualSegmentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    nsdb.LocationPackage.LocVirtualSegmentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return nsdb.LocationPackage.LocVirtualSegmentHelper.type ();
  }

}
