package type;


/**
* type/Fuzzy.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public final class Fuzzy implements org.omg.CORBA.portable.IDLEntity
{
  public int value = (int)0;
  public int size = (int)0;
  public int type = (int)0;

  public Fuzzy ()
  {
  } // ctor

  public Fuzzy (int _value, int _size, int _type)
  {
    value = _value;
    size = _size;
    type = _type;
  } // ctor

} // class Fuzzy
