package type;


/**
* type/DbXrefListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from corba/types.idl
* Monday, August 23, 2004 12:02:37 PM BST
*/

public final class DbXrefListHolder implements org.omg.CORBA.portable.Streamable
{
  public type.DbXref value[] = null;

  public DbXrefListHolder ()
  {
  }

  public DbXrefListHolder (type.DbXref[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = type.DbXrefListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    type.DbXrefListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return type.DbXrefListHelper.type ();
  }

}
